config/routes.rb
Rails.application.routes.draw do
	root "admin/customers#index"
	namespace :admin do
		resources :customers do
			resources :workpieces
		end
		resources :workpieces do
			resources :manufacturing_records
		end
		resources :factories do
			resources :procedures
		end
		resources :manufacturing_records
	end
end

app/models/admin.rb
module Admin
end

app/models/admin/contact.rb
class Admin::Contact < ApplicationRecord
	belongs_to :customer, optional: true
	belongs_to :factory, optional: true

	validates :name, :phone, uniqueness: true, presence: true
end

app/models/admin/customer.rb
class Admin::Customer < ApplicationRecord
	enum payment_term: { "cash": 0, "net30": 1 }

	has_many :workpieces
	has_many :contacts
	
	validates :name, :address, presence: true, uniqueness: true
end

app/models/admin/factory.rb
class Admin::Factory < ApplicationRecord
	has_many :procedures
	has_many :contacts

	validates :skill, presence: true
	validates :name, :address, presence: true, uniqueness: true

	def name_and_skill
		"#{self.name} - #{self.skill}"
	end
end

app/models/admin/manufacturing_record.rb
class Admin::ManufacturingRecord < ApplicationRecord
	has_secure_token

	validates :token, uniqueness: true

  belongs_to :workpiece
  has_many :procedures, dependent: :destroy

  def first_procedure
  	self.procedures.where("arrived_at IS NOT NULL").order(:arrived_at).first
  end

  def previous_procedure
  	self.procedures.where("finished_at IS NOT NULL").order(:finished_at).last
  end

  def current_procedure
  	self.procedures.where(finished_at: nil).order(:arrived_at).first
  end

  def next_procedure
  	if self.procedures.where(finished_at: nil).size > 1
  		self.procedures.where(finished_at: nil).order(:arrived_at)[1]
  	else
  		nil
  	end
  end
end

app/models/admin/procedure.rb
class Admin::Procedure < ApplicationRecord
  belongs_to :factory
  belongs_to :manufacturing_record
end

app/models/admin/workpiece.rb
class Admin::Workpiece < ApplicationRecord
	belongs_to :customer
	has_many :manufacturing_records

	validates :name, presence: true
	validates :picnum, presence: true, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
	validates :name, :address, presence: true
	enum payment_term: { "cash": 0, "net30": 1 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < AdminController
	before_action :find_customer, :set_nav_title

	def index
		@customers = Admin::Customer.all
	end

	private
	def find_customer
		@customer = Admin::Customer.find(params[:id]) if params[:id]
	end

	def set_nav_title
		@nav_title = "客戶管理"
	end
end

app/controllers/admin/factories_controller.rb
class Admin::FactoriesController < AdminController
	before_action :find_factory, :set_nav_title

	def index
		@factories = Admin::Factory.all
	end

	private
	def find_factory
		@factory = Admin::Factory.find(params[:id]) if params[:id]
	end

	def set_nav_title
		@nav_title = "加工廠管理"
	end
end

app/controllers/admin/manufacturing_records_controller.rb
class Admin::ManufacturingRecordsController < AdminController
	before_action :find_manufacturing_record, :set_nav_title

	def index
		@manufacturing_records = Admin::ManufacturingRecord.includes(:procedures, :workpiece, procedures: :factory).all
	end

	private
	def find_manufacturing_record
		@manufacturing_record = Admin::ManufacturingRecord.find(params[:id]) if params[:id]
	end

	def set_nav_title
		@nav_title = "追料"
	end
end

app/controllers/admin/procedures_controller.rb
class Admin::ProceduresController < AdminController
	before_action :find_procedure, :set_nav_title

	def index
		@procedures = Admin::Procedure.all
	end

	private
	def find_procedure
		@procedure = Admin::Procedure.find(params[:id]) if params[:id]
	end

	def set_nav_title
		@nav_title = "追料"
	end
end

app/controllers/admin/workpieces_controller.rb
class Admin::WorkpiecesController < AdminController
	before_action :find_workpiece, :set_nav_title

	def index
		@workpieces = if params[:customer_id].present?
			Admin::Workpiece.where(customer_id: params[:customer_id]).all
		else
			Admin::Workpiece.all
		end
	end

	private
	def find_workpiece
		@workpiece = Admin::Workpiece.find(params[:id]) if params[:id]
	end

	def set_nav_title
		@nav_title = "工件管理"
	end
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
	layout "admin"

	before_action :sidebar_notificatin_numbers

	def sidebar_notificatin_numbers
		@manufacturing_records = Admin::ManufacturingRecord.all
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
	def mobile?
		client = DeviceDetector.new(request.user_agent)
		return client.device_type == "smartphone"
	end

	def active_if(url)
		begin
			"active" if current_page?(url)	
		rescue Exception => e
			"active" if controller_name == url[:controller]
		end
	end
end

app/helpers/manufacturing_record_helper.rb
module ManufacturingRecordHelper
	def render_hint_based_on_arrived_at(manufacturing_record)
		has_been_these_days = how_many_days_at_current_procedure(manufacturing_record)
		if has_been_these_days > 45
			"border-danger"
		elsif has_been_these_days > 30
			"border-warning"
		else
			"border-light"
		end
	end

	def how_many_days_at_current_procedure(manufacturing_record)
		(Date.current - manufacturing_record.previous_procedure.finished_at.to_date).to_i
	end
end

app/helpers/workpiece_helper.rb
module WorkpieceHelper
  def readable_picnum(picnum)
  	content_tag :span, style: "letter-spacing: 1.5px;" do
  		small_part = picnum[0..-6]
  		big_part = content_tag :span, style: "font-size: 130%;" do
  			picnum[-5..-1]
  		end
  		raw(small_part + big_part)
  	end
  end
end

app/views/admin/customers/index.html.erb
<table class="table thead-fixed">
	<thead>
		<th>名稱</th>
		<th>地址</th>
		<th>付款方式</th>
		<th></th>
	</thead>
	<tbody>
		<% @customers.each do |customer| %>
			<tr>
				<td><%= customer.name %></td>
				<td><%= customer.address %></td>
				<td><%= customer.payment_term %></td>
				<td><%= link_to "所有工件", admin_customer_workpieces_path(customer_id: customer) %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/factories/index.html.erb
<table class="table thead-fixed">
	<thead>
		<th>名稱</th>
		<th>地址</th>
		<th>加工種類</th>
		<th></th>
	</thead>
	<tbody>
		<% @factories.each do |factory| %>
			<tr>
				<td><%= factory.name %></td>
				<td><%= factory.address %></td>
				<td><%= factory.skill %></td>
				<td><%= link_to "發包狀況", admin_factory_procedures_path(factory_id: factory) %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/manufacturing_records/index.html.erb
<table class="table thead-fixed">
	<thead>
		<th>圖號</th>
		<th>發包數量</th>
		<!-- <th>從</th>
		<th></th> -->
		<th>目前位於</th>
		<th>本站 / <small>總累積天數</small></th>
		<th></th>
		<th></th>
	</thead>
	<tbody>
		<% @manufacturing_records.each do |manu_record| %>
			<tr>
				<td>
					<%= link_to readable_picnum(manu_record.workpiece.picnum), admin_workpiece_path(manu_record.workpiece) %>
				</td>
				<td><%= manu_record.current_procedure.amount || rand(10..50) %></td>
				<!-- <td class="text-muted"><small><%#= manu_record.previous_procedure.factory.name_and_skill %></small></td>
				<td class="text-muted"><%#= I18n.l(manu_record.previous_procedure.arrived_at, format: "%b%d日(%a)") %></td> -->
				<td><%= manu_record.current_procedure.factory.name_and_skill %><small class="text-muted"> <i class="fi-arrow-right"></i> <%= manu_record.next_procedure.factory.name_and_skill %></small></td>
				<td><strong><%= (Date.current - manu_record.current_procedure.arrived_at.to_date).to_i %></strong> / <small><%= (Date.current - manu_record.first_procedure.arrived_at.to_date).to_i %></small></td>
				<td>
					<%= link_to "#" do %>
						提醒
						<i class="fi-bookmark"></i>
					<% end %>
				</td>
				<td>
					<%= link_to "#" do %>
						編輯
						<i class="fi-page-edit"></i>
					<% end %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light" id="nav">
  <a class="navbar-brand" href="#"><%= @nav_title %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor03">
    <form class="form-inline w-100 mr-1">
      <div class="input-group w-100">
	      <input type="text" class="form-control" placeholder="搜尋客戶、訂單、圖號、工廠" aria-label="搜尋">
	      <span class="input-group-btn">
	        <button id="navbar-search-btn" class="btn" type="button" style="cursor: pointer;">
	        	<i class="fi-magnifying-glass"></i>
	        </button>
	      </span>
	    </div>
    </form>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
      <!-- 以下為 mobile sidebar -->
      <% if mobile? %>
      <hr>
      <li class="nav-item">
      	<a class="nav-link" href="#">
      		訂單管理
      		<span class="badge badge-primary badge-pill">14</span>
      	</a>
      </li>
      <li class="nav-item">
      	<a class="nav-link" href="#">
      		追料
      	</a>
      </li>
      <li class="nav-item">
      	<a class="nav-link" href="#">
      		加工廠商資料
      	</a>
      </li>
      <li class="nav-item">
      	<a class="nav-link" href="#">
      		工件資料
      	</a>
      </li>
      <li class="nav-item">
      	<a class="nav-link" href="#">
      		應收帳款
      	</a>
      </li>
      <li class="nav-item">
      	<a class="nav-link" href="#">
      		應付帳款
      	</a>
      </li>
      <% end %>
      <!-- 以上為 mobile sidebar -->
    </ul>
  </div>
</nav>

app/views/admin/partials/_sidebar.html.erb
<div class="logo text-center">
	翔裕國際
</div>
<div class="list-group">
  <%= link_to admin_workpieces_path, class: "list-group-item list-group-item-action #{active_if(controller: 'workpieces')}" do %>
		工件總覽
	<% end %>
  <%= link_to admin_manufacturing_records_path, class: "list-group-item list-group-item-action #{active_if(admin_manufacturing_records_path)}" do %>
		追料
    <span class="badge badge-primary badge-pill"><%= @manufacturing_records.size %></span>
	<% end %>
  <a href="#" class="list-group-item list-group-item-action">
    訂單管理
  </a>
  <%= link_to admin_factories_path, class: "list-group-item list-group-item-action #{active_if(admin_factories_path)}" do %>
		加工廠商
    <span class="badge badge-primary badge-pill">14</span>
	<% end %>
	<%= link_to admin_customers_path, class: "list-group-item list-group-item-action #{active_if(admin_customers_path)}" do %>
		客戶
    <span class="badge badge-primary badge-pill">14</span>
	<% end %>
  <a href="#" class="list-group-item list-group-item-action disabled">應收帳款</a>
  <a href="#" class="list-group-item list-group-item-action disabled">應付帳款</a>
</div>

app/views/admin/workpieces/index.html.erb
<table class="table thead-fixed">
	<thead>
		<th>圖號</th>
		<th>名稱</th>
		<th>規格</th>
		<th>售價</th>
		<th>庫存量</th>
		<th>發包中</th>
		<th>待發包數量</th>
	</thead>
	<tbody>
		<% @workpieces.each do |workpiece| %>
			<tr>
				<td><%= workpiece.picnum %></td>
				<td><%= workpiece.name %></td>
				<td><%= workpiece.spec || "實際尺寸SCM21φ28*344" %></td>
				<td><%= number_with_delimiter(workpiece.price || rand(50..80) * 100) %></td>
				<td><%= rand(100) %></td>
				<td><%= link_to rand(100), admin_workpiece_manufacturing_records_path(workpiece_id: workpiece) %></td>
				<td><%= rand(100) %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @nav_title %> | 翔裕管理系統</title>
    <meta name="viewport" content="width=device-width">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/foundation-icons/3.0/foundation-icons.min.css">
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="admin container-fluid">
    <div class="row" id="full_page_wrapper">
      <% unless mobile? %>
        <div id="sidebar">
          <%= render "admin/partials/sidebar" %>
        </div>
      <% end %>
      <div id="right">
        <%= render "admin/partials/nav" %>
        <div id="main_content" class="px-1">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>翔裕管理系統</title>
    <meta name="viewport" content="width=device-width">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>